[package]
name = "fifth_row"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fehler = "1.0.0"
snafu = {version = "0.6.10", features = ["backtraces", "backtraces-impl-backtrace-crate"]}
